### ISSUE TITLE
Plugin breaks in private mode

### ISSUE THREAD

**Issue by laxris** [digitalmethodsinitiative/zeeschuimer#2]
When running in private mode, despite being allowed to run, the plugin fails with a Javascript error.

![image](https://user-images.githubusercontent.com/4000627/194951638-4539e9d3-f34e-4369-902c-a069f7a67d22.png)

**Comment by stijn-uva** [comment]
Apologies for the delayed response. This is difficult to fix because the method Zeeschuimer uses to access stored items, etc, is [not supported in private mode](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/getBackgroundPage). There are alternatives but they would require a comprehensive rewrite of most parts of the extensions, something I currently don't have the resources to do. If you require data collection in private mode, your best bet is probably running a separate 'research browser' not used for anything else, which would be functionally the same as running in private mode.

I will make the extension unavailable in private mode with the next release to avoid any confusion.

**Comment by laxris** [comment]
Awesome, thank you. Making it unavailable seems like a working solution.
