### ISSUE TITLE
Port 5000 in result/dataset link

### ISSUE THREAD

**Issue by 73616e646572** [digitalmethodsinitiative/zeeschuimer#20]
After gathering data with Zeeschuimer, a result link is generated combining the given 4CAT server URL with a public port number (inserting `:5000`). 

![image](https://github.com/digitalmethodsinitiative/zeeschuimer/assets/6605233/efb4cb14-672a-4268-a3c0-90370bc96fbb)

On our servers the usage of port 5000 within the container is possible, but we cannot open this port publicly. As a result, this leads to a connection timeout error, as the server cannot be accessed through this port.

Would any of the following be possible?
1. Making the public port number in result links optional.
2. Making the public port setting adjustable, so that we could for example use port 443.
3. Leaving the port number out the result links (resulting in: `https://my-4cat.link/results/`).

**Comment by dale-wahl** [comment]
I believe this was fixed, but ZeeSchuimer displays the URL received from 4CAT. What version of 4CAT are you using?

**Comment by 73616e646572** [comment]
1.38 as well as 1.36.

**Comment by 73616e646572** [comment]
One is still on 1.36, the rest is on 1.38. Zeeschuimer version 1.8.0.

**Comment by stijn-uva** [comment]
Does the value for 'Host name' in the 4CAT settings (Flask Settings -> Host name) include the `:5000` port number?

**Comment by 73616e646572** [comment]
It was indeed included, although the port number had been removed from the host name before. 

After removing the port number again and having a new dataset collected, it unfortunately still results in the same:
![image](https://github.com/digitalmethodsinitiative/zeeschuimer/assets/6605233/d05bd488-10ba-481a-9c46-63e12d10668d)

**Comment by stijn-uva** [comment]
Since this is a Flask setting, it requires restarting the front-end for it to take effect everywhere. Note that I am not 100% sure this will help, but it seems worth trying...

**Comment by dale-wahl** [comment]
`docker_setup.py` runs every time the 4CAT backend container starts and it updates `flask.server_name` by appending the `PUBLIC_PORT` from the `.env` file. That is why that value updates. This, so far as I can tell, should not affect what you are seeing here since `flask.server_name` is not passed to Flask in a Docker setup.

Flask _might_ be getting your server name from the `SERVER_NAME` set in your `.env` file (as that value is written to the operating system environment by Docker). If you have `my-4cat.link:5000` set in your `.env` file for `SERVER_NAME` that could explain this behavior. Otherwise, I do not know.

**Comment by dale-wahl** [comment]
this commit https://github.com/digitalmethodsinitiative/4cat/commit/0c179e9150a08810e914c166e2dd70472172fa8f will stop 4CAT from appending the port to your `flask.server_name` setting on startup. It will instead warn users and inform them how to update the setting if needed/desired. It may help with your situation though I still do not understand how Flask is retrieving that `SERVER_NAME` since we do not set it to the `flask.server_name` in Docker setups.
