### ISSUE TITLE
Extension does not provide correct X-Zeeschuimer-Platform header for 9gag.com 

### ISSUE THREAD

**Issue by eamonnbell-dur** [digitalmethodsinitiative/zeeschuimer#22]
**Steps to reproduce:**

1. Install Zeeschuimer
2. Enable collection for 9gag.com
3. Visit 9gag.com, ingest posts into Zeeschuimer (item count increases)
4. Click "to 4CAT"
5. Error "The 4CAT server does not accept 9gag.com datasets. The 4CAT administrator may need to enable the data source or upgrade 4CAT."

The response from the `/api/import-dataset` is 404, "Unknown platform or source format"

**Possible cause:**

I have located this issue in the value provided in the `X-Zeeschuimer-Platform` header, which is currently `9gag.com`. 

This is is not a recognised data source on the 4CAT side: https://github.com/digitalmethodsinitiative/4cat/blob/master/datasources/ninegag/__init__.py#L11.

**Comment by stijn-uva** [comment]
Hi @eamonnbell-dur, thanks for reporting. We'll have to fix this in 4CAT itself since changing the internal identifier used in Zeeschuimer would break existing datasets, which probably would not be a significant inconvenience for most users but could still result in a loss of data. As of https://github.com/digitalmethodsinitiative/4cat/commit/b3aee4da108d7e7ef3f4d1094415bfb1b86e354a 4CAT will accept 9gag imports (and this fix will be in the next 4CAT release).
