### ISSUE TITLE
Refreshing image URLs?

### ISSUE THREAD

**Issue by laxris** [digitalmethodsinitiative/zeeschuimer#3]
I guess this is more of a feature request, and maybe zeeschuimer isn't the right place for it.

I didn't realize that titok preview URLs have a limited lifetime and now my dataset has a lot of stale links in it. Is there an easy way to take the titok URLs and rerun zeeschuimer to get fresh image URLS?

**Comment by dale-wahl** [comment]
Good request. I noticed the exact same thing on a dataset of mine; annoying as I was going to download all the videos and the links were dead. I'm not sure how we would do that in ZeeSchuimer as it would involve revisiting the posts to extract new links (as opposed to monitoring posts you visit and collecting data).

Do we know if the URLs change in a predictable way? If so, it could be a simple conversion (and we could add a field on export that says "expected_current_url" or something similar). I haven't checked, but one could look at a single post and see how the URL changes over time to get an idea.

**Comment by stijn-uva** [comment]
URLs do not change in a predictable way, unfortunately. Zeeschuimer is not set up to 'refresh' these as doing so would require another roundtrip to the TikTok posts' page to fetch the latest metadata.

[4CAT](https://github.com/digitalmethodsinitiative/4cat) does have a 'TikTok URLs' data source that can fetch metadata for a given list of TikTok post URLs. You could feed it the list of TikTok URLs in your initial dataset and re-fetch the metadata that way, though it could take a while (and posts that have been deleted in the meantime would not be included).

Note that there are two thumbnails: one in `video->cover` and the other in `video->shareCover`. One of the two (I think the latter) is available for longer than the other. A timestamp is embedded in the URL that indicates when it will expire (as the `x-expires` parameter).

I am closing this as `wontfix` since it is not something Zeeschuimer can really address on its own but hopefully these suggestions are helpful.

**Comment by laxris** [comment]
Yeah, I figured that it's unavoidable to go back to the post-URL using the post-id and then grab a fresh image. I'll check out 4CAT's functionality, I think that does fit the bill. Thanks for both of your feedback!
